### create a new brand
POST http://localhost:1000/api/brands
Content-Type: application/json

{
  "name": "brands 2"
}

### get all brandss
GET http://localhost:1000/api/brands


### get a brands by id
GET http://localhost:1000/api/brands/6807a7e780d6c466803737de



### update a brands by id

PATCH http://localhost:1000/api/brands/6807a7e780d6c466803737de
Content-Type: application/json

{
  "name": "Updated Brands 1"
}


### delete a brands by id
DELETE http://localhost:1000/api/brands/6807edf62b31ff74fb361bc3

